### ISSUE TITLE
feat: add OpenSearch description format

### ISSUE THREAD

**Issue by scratchmex** [approach0/ui-approach0#2]
Add  the OpenSearch description format to be allow to add it as a search engine in Firefox.

ref: https://developer.mozilla.org/en-US/docs/Web/OpenSearch
ref: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox

**Comment by w32zhong** [comment]
@scratchmex Thanks for your suggestion.

I've added a simple OpenSearch XML (see 292a3461131350b47aa9ac7d8bcb7244a9caada1), however, our math search query requires many changes to adapt  `{searchTerms}` template parameter, because query like `foo,bar` in our case needs to be canonicalized into `OR content:foo, OR content:bar`. I don't see an easy way to get this working quickly, so I will stop here and leave this issue open.

**Comment by w32zhong** [comment]
This issue has been resolved in recent commits. @scratchmex, thanks for the suggestion here.
